openapi: 3.0.0
info:
  version: 1.0.0
  title: Travel Billing
  description: The Travel Invoicing Application System
servers:
  - url: https://api.esgi.fr/billing/v1
paths:
  /operations:
    get:
      tags:
        - Operations
      description: Returns a list of Operation added to deferred billing
      parameters:
        - $ref: '#/components/parameters/QueryInvoiceRef'
      responses:
        '200':
          description: Successfully returned a list of Operations
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/OperationsResponse'
              examples:
                OperationsResponse:
                  $ref: '#/components/examples/OperationsResponse'
        '401':
          description: ERROR - Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '403':
          description: ERROR - Access token does not have the required scope
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '500':
          description: ERROR - Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
    post:
      tags:
        - Operations
      summary: Add Operations
      description: Add a new Operation to deferred billing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationRequest'
            examples:
              OperationRequest:
                $ref: '#/components/examples/OperationRequest'
      responses:
        '201':
          description: Operation successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              examples:
                OperationResponse:
                  $ref: '#/components/examples/OperationResponse'
        '401':
          description: ERROR - Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '403':
          description: ERROR - Access token does not have the required scope
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '500':
          description: ERROR - Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
  /invoices:
    get:
      tags:
        - Invoices
      description: Returns a list of Invoices
      responses:
        '200':
          description: Successfully returned a list of Invoices
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoices:
                    type: array
                    items:
                      $ref: '#/components/schemas/Invoice'
        '401':
          description: ERROR - Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '403':
          description: ERROR - Access token does not have the required scope
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '500':
          description: ERROR - Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
  /invoices/{invoiceRef}:
    get:
      tags:
        - Invoices
      description: Returns an invoice
      parameters:
        - $ref: '#/components/parameters/PathInvoiceRef'
      responses:
        '200':
          description: Successfully returned a list of invoices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '401':
          description: ERROR - Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '403':
          description: ERROR - Access token does not have the required scope
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
        '500':
          description: ERROR - Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SubscriptionsResponse:
                  $ref: '#/components/examples/ErrorResponse'
components:
  parameters:
    PathInvoiceRef:
      name: invoiceRef
      in: path
      description: External identifier of the invoice
      required: true
      example: BIL-HGDU12687628
      schema:
        type: string
    QueryInvoiceRef:
      name: invoiceRef
      in: query
      description: External identifier of the invoice
      schema:
        type: string
  schemas:
    ErrorType:
      type: object
      required:
        - path
        - timestamp
        - errorCode
        - status
      properties:
        path:
          type: string
        timestamp:
          type: integer
        errorCode:
          type: string
        status:
          type: integer
        message:
          type: string
        detail:
          type: string
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorType'
    BusinessAddress:
      description: >
        A postal address splitted in 6 lines ordered as defined in RNVP and
        french standard AFNOR NF Z 10-011

        ([more information about the
        standards](http://www.rnvp-internationale.com/norme-postale/NF-Z-10-011.php)).

        All the lines are mandatory. Lines that are optional may be empty.
      type: object
      properties:
        line1:
          description: |
            Particular: CIVILITÉ - TITRE ou QUALITÉ - PRÉNOM - NOM
            Progessionnal: RAISON SOCIALE ou DÉNOMINATION
          type: string
          example: ESGI SA
        line2:
          description: |
            Particular: N°APP ou BAL - ÉTAGE - COULOIR - ESC
            Professionnal: IDENTITÉ DU DESTINATAIRE et ou SERVICE
          type: string
          example: Service comptabilité
        line3:
          description: ENTRÉE - BÂTIMENT - IMMEUBLE - RÉS - ZI
          type: string
          example: null
        line4:
          description: NUMÉRO - LIBELLÉ DE LA VOIE
          type: string
        line5:
          description: LIEU DIT ou SERVICE PARTICULIER DE DISTRIBUTION
          type: string
        locality:
          description: Name of the locality of the address
          type: string
        countryCode:
          description: >-
            Country code as defined in standard ISO 3166 ([more information
            about the
            standard](https://www.iso.org/fr/iso-3166-country-codes.html))
          type: string
        countryName:
          description: >-
            Country name as defined in standard ISO 3166 ([more information
            about the
            standard](https://www.iso.org/fr/iso-3166-country-codes.html))
          type: string
    BusinessPerson:
      type: object
      required:
        - lastName
        - mail
      properties:
        gender:
          description: Gender of the contact
          type: string
          enum:
            - M
            - MME
          example: M
        firstName:
          description: First name of the contact
          type: string
          example: John
        lastName:
          description: Last name of the contact
          type: string
          example: DOE
        mail:
          description: Mail address of the contact
          type: string
          format: email
          example: john.doe@acme.com
        phone:
          description: Phone number of the contact
          type: string
          format: phone
          example: +33 (0)1 56 87 65 78
    Invoice:
      description: Describe an invoice
      type: object
      required:
        - invoiceId
        - operations
      properties:
        invoiceId:
          description: Invoice Id
          type: string
        operations:
          type: array
          items:
            $ref: '#/components/schemas/OperationResponse'
    OperationRequest:
      description: Describes an Operation added to deferred billing
      type: object
      required:
        - orderRef
      properties:
        contractId:
          description: Contract Id
          type: string
          example: CONTRACT-HGDU12687628
        customerRef:
          description: External identifier of the Customer
          type: string
          example: HA-8768376537
        operationAt:
          description: >
            Transaction date in the sales system as defined in ISO 8601 ([more
            information about the
            standar](https://www.iso.org/fr/iso-8601-date-and-time-format.html)). 

            Used format : YYYY-MM-DD
          type: string
          format: date
          example: '2022-04-27'
        contact:
          description: Contact of the customer
          type: object
          properties:
            ccuid:
              description: CCUID
              type: string
              example: CCUID-HGDU12687628
            gender:
              description: Gender of the contact
              type: string
              enum:
                - M
                - MME
              example: M
            firstName:
              description: First name of the contact
              type: string
              example: John
            lastName:
              description: Last name of the contact
              type: string
              example: DOE
            mail:
              description: Mail address of the contact
              type: string
              format: email
              example: john.doe@acme.com
            phone:
              description: Phone number of the contact
              type: string
              format: phone
              example: +33 (0)1 56 87 65 78
        order:
          description: Describes Purchase or Refund Operation
          type: object
          properties:
            orderRef:
              description: External Order reference
              type: string
              example: 789e4567-e89b-12d3-a456-556642440000
            currencyCode:
              description: >-
                Billing currency code as defined in ISO 4217 ([more information
                about the
                standard](https://www.iso.org/fr/iso-4217-currency-codes.html))
              type: string
              example: EUR
            orderType:
              description: |
                Necessary for e-Invoicing : 
                LB = Livraison de Biens,
                PS = Prestation de Service
                LBPS = Double
              type: string
              enum:
                - LB
                - PS
                - LBPS
              example: LB
            orderItems:
              type: array
              items:
                type: object
                properties:
                  shipmentAddress:
                    $ref: '#/components/schemas/BusinessAddress'
                  shipmentContact:
                    $ref: '#/components/schemas/BusinessPerson'
                  deliveredOn:
                    description: Order delivery date
                    type: string
                    format: date
                    example: '2022-04-28'
                  productItems:
                    type: array
                    items:
                      type: object
                      properties:
                        productRef:
                          type: string
                        productLabel:
                          type: string
                        quantity:
                          type: integer
                        packaging:
                          type: string
                        unitPrice:
                          type: number
                        vatRate:
                          type: number
                        amountWithoutTax:
                          type: number
                        amountTax:
                          type: number
                        amountWithTax:
                          type: number
                        amountEcoParticipation:
                          description: Necessary for e-Invoicing
                          type: number
            totalWithoutTax:
              type: number
            totalTax:
              type: number
            totalWithTax:
              type: number
            amountEcoParticipation:
              description: Necessary for e-Invoicing
              type: number
      example:
        $ref: '#/components/examples/OperationRequest'
    OperationResponse:
      allOf:
        - type: object
          properties:
            operationId:
              description: Internal identifier of the Operation
              type: string
              example: 123e4567-e89b-12d3-a456-556642440000
            operationRef:
              description: External identifier of the Operation
              type: string
              example: HA-8768376537
            billing:
              type: object
              properties:
                subscriptionRef:
                  type: string
                createdAt:
                  type: string
                  format: date
            invoice:
              type: object
              properties:
                invoiceRef:
                  type: string
                createdAt:
                  type: string
                  format: date
        - $ref: '#/components/schemas/OperationRequest'
      example:
        $ref: '#/components/examples/OperationResponse'
    OperationsResponse:
      description: List of operations that meet the search criteria
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/OperationResponse'
        metadata:
          $ref: '#/components/schemas/QueryMetadataResponse'
      example:
        OperationssResponse:
          $ref: '#/components/examples/OperationsResponse'
    QueryMetadataResponse:
      description: Informations on current query & count of items and pages
      type: object
      properties:
        query:
          description: URI of current query
          type: string
        countItems:
          description: Number of items in current response
          type: integer
        totalItems:
          description: Total number of items for current query
          type: integer
        totalPages:
          description: Total number of pages for current query
          type: integer
  examples:
    ErrorResponse:
      value:
        errors:
          - path: /currentPath
            timestamp: 2022-04-28-16T22:14:45.624+0000
            errorCode: PD-123
            status: 400|401|403|500
            message: Error message
    OperationRequest:
      value:
        contractId: CONTRACT-HGDU12687628
        customerRef: HA-8768376537
        operationAt: '2022-04-27'
        contact:
          ccuid: CCUID-HGDU12687628
          firstName: John
          lastName: DOE
          mail: john@mail.com
          phone: +33 (0)1 56 87 65 78
        order:
          - orderRef: 444e4567-e89b-12d3-a456-556642440000
            orderType: LB
            shipmentAddress: null
            shipmentContact:
              - productRef: '1116420'
                productLabel: Carnet de 12 timbres Marianne Vert - Lettre verte
                quantity: 1
                packaging: PCE
                unitPrice: 8.4
                vatRate: 5.5
                amountWithoutTax: 8.4
                amountTax: 0.46
                amountWithTax: 8.86
              - productRef: null
                productLabel: Frais de port
                quantity: 1
                packaging: PCE
                unitPrice: 2.8
                vatRate: 20
                amountWithoutTax: 2.8
                amountTax: 0.59
                amountWithTax: 3.39
            totalWithoutTax: 11.2
            totalTax: 1.05
            totalWithTax: 12.25
        billing:
          subscriptionRef: SUB-YTYE65687
          createdAt: '2022-04-22'
    OperationResponse:
      value:
        operationId: 867658
        operationRef: HA-8768376537
        customerRef: HA-8768376537
        operationAt: '2022-04-27'
        order:
          - shipmentAddress: null
            shipmentContact:
              - productRef: '1116420'
                productLabel: Carnet de 12 timbres Marianne Vert - Lettre verte
                quantity: 1
                packaging: PCE
                unitPrice: 8.4
                vatRate: 5.5
                amountWithoutTax: 8.4
                amountTax: 0.46
                amountWithTax: 8.86
              - productRef: null
                productLabel: Frais de port
                quantity: 1
                packaging: PCE
                unitPrice: 2.8
                vatRate: 20
                amountWithoutTax: 2.8
                amountTax: 0.59
                amountWithTax: 3.39
            totalWithoutTax: 11.2
            totalTax: 1.05
            totalWithTax: 12.25
        billing:
          subscriptionRef: SUB-YTYE65687
          createdAt: '2022-04-22'
    OperationsResponse:
      value:
        operations:
          - operationId: 867658
            operationRef: HA-8768376537
            customerRef: HA-8768376537
            operationAt: '2022-04-27'
            order:
              - shipmentAddress: null
                shipmentContact:
                  - productRef: '1116420'
                    productLabel: Carnet de 12 timbres Marianne Vert - Lettre verte
                    quantity: 1
                    packaging: PCE
                    unitPrice: 8.4
                    vatRate: 5.5
                    amountWithoutTax: 8.4
                    amountTax: 0.46
                    amountWithTax: 8.86
                  - productRef: null
                    productLabel: Frais de port
                    quantity: 1
                    packaging: PCE
                    unitPrice: 2.8
                    vatRate: 20
                    amountWithoutTax: 2.8
                    amountTax: 0.59
                    amountWithTax: 3.39
                totalWithoutTax: 11.2
                totalTax: 1.05
                totalWithTax: 12.25
            billing:
              subscriptionRef: SUB-YTYE65687
              createdAt: '2022-04-22'
        metadata:
          query: /subscriptions?customerRef=124&status=ACTIVE
          countItems: 1
          totalItems: 1
          totalPages: 1